export const HOME_SCENE_NODE_NAMES = {
  root: "HomeRoot",
  safeAreaRoot: "SafeAreaRoot",
  titleArea: "TitleArea",
  summaryPanel: "SummaryPanel",
  levelPanel: "LevelPanel",
  actionPanel: "ActionPanel",
  summaryLabel: "SummaryLabel",
  levelLabel: "LevelLabel",
  levelDetailLabel: "LevelDetailLabel",
  statusLabel: "StatusLabel",
  prevLevelButton: "PrevLevelButton",
  nextLevelButton: "NextLevelButton",
  selectLevelButton: "SelectLevelButton",
  startLevelButton: "StartLevelButton",
  startLevelButtonLabel: "StartLevelButtonLabel",
  shareButton: "ShareButton",
  shareButtonLabel: "ShareButtonLabel",
  resetProgressButton: "ResetProgressButton",
} as const;

export const MAIN_SCENE_NODE_NAMES = {
  root: "GameRoot",
  managers: "Managers",
  world: "World",
  ui: "UI",
  safeAreaRoot: "SafeAreaRoot",
  mapLayer: "MapLayer",
  buildSpotLayer: "BuildSpotLayer",
  towerLayer: "TowerLayer",
  enemyLayer: "EnemyLayer",
  bulletLayer: "BulletLayer",
  effectLayer: "EffectLayer",
  topHud: "TopHUD",
  resourceBar: "ResourceBar",
  phaseBar: "PhaseBar",
  actionButtons: "ActionButtons",
  buildToolbar: "BuildToolbar",
  towerPanel: "TowerPanel",
  towerPanelActions: "TowerPanelActions",
  platformDebugPanel: "PlatformDebugPanel",
  debugInfoLabel: "DebugInfoLabel",
  livesLabel: "LivesLabel",
  goldLabel: "GoldLabel",
  waveLabel: "WaveLabel",
  killsLabel: "KillsLabel",
  bestWaveLabel: "BestWaveLabel",
  phaseLabel: "PhaseLabel",
  buildModeLabel: "BuildModeLabel",
  startWaveButton: "StartWaveButton",
  startWaveButtonLabel: "StartWaveButtonLabel",
  pauseButton: "PauseButton",
  pauseButtonLabel: "PauseButtonLabel",
  restartButton: "RestartButton",
  rapidButton: "RapidButton",
  cannonButton: "CannonButton",
  frostButton: "FrostButton",
  clearBuildSelectionButton: "ClearBuildSelectionButton",
  towerPanelTitle: "TowerPanelTitle",
  towerInfoLabel: "TowerInfoLabel",
  upgradeValueLabel: "UpgradeValueLabel",
  sellValueLabel: "SellValueLabel",
  actionHintLabel: "ActionHintLabel",
  upgradeButton: "UpgradeButton",
  sellButton: "SellButton",
} as const;

export const RESULT_SCENE_NODE_NAMES = {
  root: "ResultRoot",
  resultPanel: "ResultPanel",
  resultActions: "ResultActions",
  titleLabel: "ResultTitle",
  resultLabel: "ResultLabel",
  actionHintLabel: "ActionHintLabel",
  nextLevelButton: "NextLevelButton",
  nextLevelButtonLabel: "NextLevelButtonLabel",
  retryButton: "RetryButton",
  backHomeButton: "BackHomeButton",
  shareButton: "ShareButton",
  shareButtonLabel: "ShareButtonLabel",
} as const;
